AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: [array, hash]

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/rails_helper.rb

Lint/MissingSuper:
  Enabled: false
